var rule = {
  title: '可可影视',
  host: 'https://keke5.app',
  url: '/show/fyclass-----2-fypage.html',
  searchUrl: '/search?k=**&page=fypage',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  class_parse: '.swiper-slide.nav-swiper-slide a:gt(1):lt(8);a&&Text;a&&href;/(\\w+).html',
  cate_exclude:'今日更新|专题列表|排行榜',
  play_parse: true,
  lazy: '',
  limit: 20,
  推荐: '.section-box:eq(2)&&.module-box-inner&&.module-item;*;*;*;*',
  double: false,
  一级: '.module-box-inner&&.module-item;.v-item-title:eq(-1)&&Text;img&&src;.v-item-bottom&&span&&Text;a&&href',
  二级: {
    title: '.detail-title&&Text;.detail-tags&&a&&Text',
    img: '.detail-pic&&img&&src',
    desc: '.detail-info-row:eq(3)&&.detail-info-row-main&&Text;.detail-info-row:eq(2)&&.detail-info-row-main&&Text;.detail-info-row:eq(1)&&.detail-info-row-main&&Text;.detail-info-row:eq(0)&&Text',
    content: '.detail-desc&&Text',
    tabs: '.source-item-label',
    lists: '.episode-list:eq(#id) a',
  },
  搜索: '.search-result-list&&a;.title&&Text;.lazyload&&src;.search-result-item-header&&Text;a&&href;.desc&&Text',
}