var rule = {
  编码:'gb18030',  
  类型:'听书',
  title:'有声小说吧',
  host:'http://www.ysxs8.top/',
  url:'/downlist/fyclass_fypage.html',
  searchUrl:'/search.asp?page=fypage&searchword=**&searchtype=-1',
  searchable:2,
  quickSearch:0,
  filterable:1,
  filter:'',
  filter_url:'',
  filter_def:{},
  headers:{
      'User-Agent':'MOBILE_UA',
  },
  timeout:5000,
  class_name:'多人广播剧&网络玄幻&盗墓探险&恐怖悬疑&都市言情&传统武侠&职场商战&百家讲坛&历史文化&人物传记&有声文学&评书&相声戏曲&儿童读物',
  class_url:'r18&r52&r45&r17&r13&r12&r81&r32&r15&r16&r41&r3&r7&r4',
  cate_exclude:'',
  play_parse:true,
  lazy:$js.toString(()=>{
    input = {parse:1,url:input,js:''};
  }),
  double:true,
  一级:'.channel_left .test1;a:eq(1)&&Text;img&&src;a:eq(2)&&Text;a&&href',
  二级:{
    title:'h1&&Text;.content_center&&a:eq(3)&&Text',
    img:'.content_right&&img&&src',
    desc:';;.content_center:eq(1)&&Text;.content_center&&font&&Text',
    content:'.content_center2&&Text',
    tabs:'h2',
    lists:'.playlist:eq(#id)&&a',
    tab_text:'body&&Text',
    list_text:'body&&Text',
    list_url:'a&&href',
    list_url_prefix: '',
  },
  搜索:'.list_container li;*;*;*;*',
}