var rule = {
  title: '萌番动漫',
  host: 'https://www.mfan.tv',
  url: '/show/fyclassfyfilter/page/fyfypage/',
  searchUrl: '/search/wd/**/page/fypage/',
  searchable: 2,
  quickSearch: 0,
  filterable: 1,
  filter: 'H4sIAAAAAAAAA+2Wy07bUBCG38Xr4EB2ZWfIzQSSkCtQsUhTV0WkWMqFqkJILbQiQAMsIKFKb1RFjUpToFRqSii8DMcmb9EYx799hg0PkKW/78/MsayZnCXBMygMP1wS5pUXwrCgVU/0ve+CS1jIPFOcz4uZXEm5DS50cWetYphmvfNy3ZBd5C48VZ+7PYNuYXl22WXVY82adlyx6+GZr8feNDqrjV4lwfi5QSWrdE4pFpW8W4IZIWYEZpSYURgvMV4YHzE+GD8xfpgAMQGYIDFBGJkYGWaMmDGYEDEhmHFixmEmiJmACRMThokQE4GJEhOFmSRmEiZGTAwmTkwcJkFMAiZJTBImRUwKJk1MGmaKmCmYaWKmYWaImYEZHHhAnEG6IzDrEjxDjsnST9vs46Y9CXi+zyRorzb18qnVKJvLFAruHkPk8wGrN0nEZFaE7Wyxn0d8pMdQ5Vdbe10mVUyGSO2QtVokYjI02vrEynXSyGSoUt7XqjVSxWRWRH93yXbIWXoMjSrVm5V10shkaHRxpO+2td2/pBcwgq2WVt6+GwRG04uV61ZV33tL+gKj4tlB58OX3v50VAS2gjf/2uxk++b4953unMGspiQ+ZQBIyUukZG+66/Mfnf0rdnLBR2yME22cadU1/eslOQ4wdvTAUHQuWyzllQIfdQos55y6qOTTan6ehJ0CO1EcFeMJye/nozbG99hodD8l+3Oola/IJ3EabKBkOCbHfXzSglh6efVxKVucUxdEWQzwWeKwdSVvUC0VFD4Mir+uSNgX5zMmQmtREtORWIiEbIwXCUr+BHmNW2SfKBqV6HEMZAVKT9Ri5lGOHBkUmzkmBwK+GJ+yIBaunIgnkl45wsds3L8W9K8F/WuBcS3wOK4FbP0be3/umATr+b4Xbk//wt2frP5kdSdr+T9WIk4GzA4AAA==',
  filter_url:'{{fl.类型}}{{fl.字母}}',
  class_name:'新番&番剧&剧场',
  class_url:'20&21&22&4&20',
  play_parse: true,
  lazy: '',
  limit: 6,
  推荐: '.module-list;.module-items&&.module-item;a&&title;img&&data-src;.module-item-text&&Text;a&&href',
  double: true,
  一级: '.hl-vod-list&&li;a&&title;a&&data-original;.hl-pic-text&&Text;a&&href',
  二级: {
    title: '.hl-dc-title&&Text;.hl-pic-tag&&span&&Text;.hl-col-xs-12:eq(11)&&Text;.hl-col-xs-12:eq(7)&&Text',
    img: '.hl-item-thumb&&data-original',
    desc: '.hl-col-xs-12:eq(2)&&Text;.hl-col-xs-12:eq(7)&&Text;.hl-col-xs-12:eq(5)&&Text;.hl-col-xs-12:eq(6)&&Text;.hl-col-xs-12:eq(4)&&Text',
    content: '.hl-col-xs-12:eq(12)&&Text',
    tabs: '.hl-plays-from',
    lists: '.hl-plays-list:eq(#id)&&a',
  },
  搜索: '.hl-one-list&&li;a&&title;a&&data-original;.hl-pic-text&&Text;a&&href',
}